source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CodFis-Helper_Example'do
  pod "CodFis-Helper", :path => "../"
end

target 'CodFis-Helper_Tests' do
  pod "CodFis-Helper", :path => "../"

  pod 'FBSnapshotTestCase'
  
end
