source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CodFis-Helper_Example', :exclusive => true do
  pod "CodFis-Helper", :path => "../"
end

target 'CodFis-Helper_Tests', :exclusive => true do
  pod "CodFis-Helper", :path => "../"

  pod 'FBSnapshotTestCase'
end
