source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

pod 'NSString-Helper' , :git => 'https://github.com/giuseppenucifora/NSString-Helper.git'

target 'CodFis-Helper_Example', :exclusive => true do
  pod "CodFis-Helper", :path => "../"
end

target 'CodFis-Helper_Tests', :exclusive => true do
  pod "CodFis-Helper", :path => "../"

  pod 'FBSnapshotTestCase'
  
end
